---
title: "Household survey data processing"
format: html
editor: source
---


## Food items & dealing with others

### Data processing - changes:

1. We made some changes on the units (NSU) and the foods reported under "other"/ "specify". The updated consisted in making those changes in a new variable in other to keep the original variable as it was. This is good for further/ future analysis and/or reference during the cleaning/analysis steps. 

For the units the new variable which contains the amended codes is called `unit_code_st` while for the variable that contains the amendment codes is called `item_code_st`.

2. Food items labelled as "others". 

'FRESHBEANS', 'GROUND AND COOKED BEANS' was allocated to item (302 - beans brown), although it may be better to keep them as "Other(nuts/pulses)". Some foods in the category others could be kept and as they are. 

## Non-standard units for own production

Assumptions under units reported as "others" (prod_unitA==23):

"PLATE" under item code 23, we are using the unit code = 6. 
"NO. 24 PLATE" under 7B
"SPOON" was assigned to "TEASPOON" unit_code(20)
"TINA (FLAT)" - 25A
"TINA (HEAPED)" , "MEDIUM (PLATE)" - 25B
"20L PAIL" - 4 


Further info is needed for:



- The unit under "heap" have two type of small to large. It should be further checked!

Units not found in the master NSU file (nsu.factor):

- Bottle as it is not reported. 
- Jar is not reported
- Pot
- Slice
- Dengu --> Container (bamboo)


Finally, what we have done is that we have used the "consumed items" cleaned and assigned the same quantity as the code/quantities were the same. 


We also identify some items wrongly code, so the item_code should be 102 instead of 101. We are amending it in the "1_ihs4_cleaning.Rmd"

We haven't been able to find the code for NSU for own production, such as c("29", "38", "39", "28", "40", "30").

After all the steps 19 items were left without a conversion from NSU to NS. None of which were maize and maize products. 

We have calculate the mean consumption (kg/d) by region for own production and total consumption. Some interesting results, like overall mean consumption and own production of maize and maize products is very similar with the exception of maize cooked (boiled or roasted) which was not reported as "own production". 

Additionally, the mean consumption of maize refined flour is marginally lower than the mean of own production for all three regions and remarkably high for "ufa madeya" in the northern region. Similarly higher consumption from own production is shown for green maize with higher contribution in the southern region. 

These results are preliminary as no weights were applied, also the results are not representative as it compares those reporting own production with all cases (all reporting consumption). 

We have instead calculated the percentage of own production from all consumed, and some interesting result are showing with differences by food item, region and residency. 

The next step should include weights, and check by different months and district/ EAs. 

Additionally, spatial pattern may arise, so it may be interesting to apply the same model or to create a variogram to see if there is any spatial dependency. It may be worth to adjust/ account for differences in HH size. 


## Household food allocation


## To-dp list

### AME/AFE function

### Testing allocations
