---
title: "factors"
author: "Kevin Tang"
date: "3/2/2020"
output: html_document
---

CREATE MASTER LIST FOR UNIT CONVERSION FACTORS

```{r}
#Create data frame only of food items actually consumed by HH
consed <- ihs4 %>% filter(cons_quant != 0) %>% arrange(id)

#Create unique ID for food item-unit combo
consed$measure_id <- paste0(as.character(consed$item_code),"_", as.character(consed$cons_unitA))

#Create new data frame listing each food item-unit unique ID
d4 <- consed %>% count(., "measure_id") %>% arrange(desc(freq))
```

Import list of all conversion factors together into one master list
```{r}
#Edward's unit
uconv_ed <- read.csv(here::here("data", "unit_conversion.csv"))
uconv_ed <- uconv_ed %>% select(MeasureID, StandardUnit)
unitconv <- merge(x=d4, y=uconv_ed, by.x='measure_id', by.y='MeasureID', fill=-9999, all.x = TRUE)

#World Bank Non-Standard Units for the Collection of Food Quantity Guidebook (IHS3)
wb_ihs4a <- read.csv(here::here("data", "ihs4factors_v2.csv"))
uconv_wb_mwi4 <- wb_ihs4a %>% select(measure_id, wbihs4fac_n, wbihs4fac_c, wbihs4fac_s)
unitconv <- merge(x=unitconv, y=uconv_wb_mwi4, by.x='measure_id', by.y='measure_id', fill=-9999, all.x = TRUE)

#World Bank Non-Standard Units for the Collection of Food Quantity Guidebook (IHS4)
uconv_wb_mwi <- read.csv(here::here("data", "wb_conv_factors_mwi.csv"))
uconv_wb_mwi3 <- uconv_wb_mwi %>% select(measure_id, wb_factor_n, wb_factor_c, wb_factor_s)
unitconv <- merge(x=unitconv, y=uconv_wb_mwi3, by.x='measure_id', by.y='measure_id', fill=-9999, all.x = TRUE)

#IFPRI Conversion Factors IHS3
uconv_ifpri_mwiihs3 <- read.csv(here::here("data", "ifpri_conv_mwiihs3.csv"))
uconv_ifpri_mwiihs3$measure_id <-paste0(as.character(uconv_ifpri_mwiihs3$itemcode),"_", as.character(uconv_ifpri_mwiihs3$unitcode))
unitconv <- merge(x=unitconv, y=uconv_ifpri_mwiihs3, by.x='measure_id', by.y='measure_id', fill=-9999, all.x = TRUE)

#IFPRI Conversion Factors IHS2
uconv_ifpri_mwiihs2 <- read.csv(here::here("data", "ifpri_conv_mwiihs2.csv"))
uconv_ifpri_mwiihs2$measure_id <-paste0(as.character(uconv_ifpri_mwiihs2$itemcode),"_", as.character(uconv_ifpri_mwiihs2$unitcode))
uconv_ifpri_mwiihs2 <- uconv_ifpri_mwiihs2 %>% select(measure_id, cf_ihs2)
unitconv <- merge(x=unitconv, y=uconv_ifpri_mwiihs2, by.x='measure_id', by.y='measure_id', fill=-9999, all.x = TRUE)
```


Hierarchically select IHS4 conversion factor from the available lists of conversion factors

```{r}
#New data frame cleaning up the master list of all factors
factors <- unitconv %>% select(measure_id, freq, itemname, unitname, wbihs4fac_n, wbihs4fac_c, wbihs4fac_s, wb_factor_n, wb_factor_c, wb_factor_s, cf_ihs3, cf_ihs2, uconv_ed)

#combine all factors for IHS4 according to hierarchy (WB IHS4, WB IHS3, IFPRI IHS3, IFPRI IHS2)
factors$ihs4factor_n <- factors$wbihs4fac_n
factors$ihs4factor_c <- factors$wbihs4fac_c
factors$ihs4factor_s <- factors$wbihs4fac_s

factors$ihs4factor_n[is.na(factors$ihs4factor_n)] <- as.numeric(factors$cf_ihs2[is.na(factors$ihs4factor_n)])
factors$ihs4factor_c[is.na(factors$ihs4factor_c)] <- as.numeric(factors$cf_ihs2[is.na(factors$ihs4factor_c)])
factors$ihs4factor_s[is.na(factors$ihs4factor_s)] <- as.numeric(factors$cf_ihs2[is.na(factors$ihs4factor_s)])

#Food unit codes in IHS4 without availavle factors from any other database
factors %>% filter(.,is.na(ihs4factor_n))

factors <- factors %>% select(measure_id, freq, wbfactor, ifpri3factor, ifpri2factor, edfactor, ihs4factor, item, unit) %>% arrange(., measure_id)

write.csv(factors, here::here("inter-output", "ihs4factors_v3.csv"))

```

CLEANING MASTER LIST OF UNIT CONVERSION FACTORS

```{r}
factors2 <- read.csv(here::here("inter-output", "ihs4factors_v3.csv"))
factors2 <- merge(x=factors2, y=ucode, by.x='ucode', by.y='code', fill=-9999, all.x = TRUE)
factors2 <- merge(x=factors2, y=fcode, by.x='fcode', by.y='code', fill=-9999, all.x = TRUE)

factors2[factors2$ucode == "1", "ihs4factor_n"] <- 1
factors2[factors2$ucode == "1", "ihs4factor_c"] <- 1
factors2[factors2$ucode == "1", "ihs4factor_s"] <- 1
factors2 %>% filter(ucode=="1") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

factors2[factors2$ucode == "18", "ihs4factor_n"] <- 0.001
factors2[factors2$ucode == "18", "ihs4factor_c"] <- 0.001
factors2[factors2$ucode == "18", "ihs4factor_s"] <- 0.001
factors2 %>% filter(ucode=="18") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

factors2[factors2$ucode == "34", "ihs4factor_n"] <- 0.15
factors2[factors2$ucode == "34", "ihs4factor_c"] <- 0.15
factors2[factors2$ucode == "34", "ihs4factor_s"] <- 0.15
factors2 %>% filter(ucode=="34") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

factors2[factors2$ucode == "23", "ihs4factor_n"] <- 0.15
factors2[factors2$ucode == "23", "ihs4factor_c"] <- 0.15
factors2[factors2$ucode == "23", "ihs4factor_s"] <- 0.15
factors2 %>% filter(ucode=="23") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

factors2[factors2$ucode == "41", "ihs4factor_n"] <- 0.025
factors2[factors2$ucode == "41", "ihs4factor_c"] <- 0.025
factors2[factors2$ucode == "41", "ihs4factor_s"] <- 0.025
factors2 %>% filter(ucode=="41") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

factors2[factors2$ucode == "42", "ihs4factor_n"] <- 0.05
factors2[factors2$ucode == "42", "ihs4factor_c"] <- 0.05
factors2[factors2$ucode == "42", "ihs4factor_s"] <- 0.05
factors2 %>% filter(ucode=="42") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

factors2[factors2$ucode == "43", "ihs4factor_n"] <- 0.1
factors2[factors2$ucode == "43", "ihs4factor_c"] <- 0.1
factors2[factors2$ucode == "43", "ihs4factor_s"] <- 0.1
factors2 %>% filter(ucode=="43") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

factors2 %>% filter(ucode=="65") %>% select(measure_id, ucode, ihs4factor_n, ihs4factor_c, ihs4factor_s)

write.csv(factors2, here::here("inter-output", "ihs4factors_v4.csv"))

```

CREATE VARIABLES FOR FACTORS IN N, C, S
```{r}
wb_ihs4 <- read.csv(here::here("data", "wb_ihs4_unit.csv"))
wb_ihs4$measure_id <- paste0(as.character(wb_ihs4$item),"_", as.character(wb_ihs4$unit))

north <- wb_ihs4 %>% filter(region==1) %>% select(measure_id, item, unit, ihps_plus_aug)
central <- wb_ihs4 %>% filter(region==2) %>% select(measure_id, ihps_plus_aug)
south <- wb_ihs4 %>% filter(region==3) %>% select(measure_id, ihps_plus_aug)

wb_ihs4a <- merge(x=north, y=central, by.x='measure_id', by.y='measure_id', fill=-9999, all.x = TRUE)
wb_ihs4a <- merge(x=wb_ihs4a, y=south, by.x='measure_id', by.y='measure_id', fill=-9999, all.x = TRUE)

colnames(wb_ihs4a)[4] <- "wbihs4fac_n"
colnames(wb_ihs4a)[5] <- "wbihs4fac_c"
colnames(wb_ihs4a)[6] <- "wbihs4fac_s"

write.csv(wb_ihs4a, here:here("inter-output", "wb_ihs4_unit_v2.csv"))
```

CREATE BAR CHARTS OF ALL FOOD ITEM UNITS
```{r}
factors <- read.csv(here::here("inter-output", "ihs4factors_v4.csv"))
factors2 <- melt(factors[,c('unit','ihs4factor_n','ihs4factor_c','ihs4factor_s')],id.vars = 1)
factors3 <- factors %>% select(fcode, item, unit, ihs4factor_n)
write.csv(factors3, here::here("inter-output", "factors3.csv"))

factors %>% filter(fcode==105) %>% arrange(freq) %>% ggplot(., aes(x=reorder(unit, -ihs4factor_n), y=ihs4factor_n)) +
   geom_bar(stat = "identity") +
   coord_flip()+
   labs(y = "Factor (in kg)")
   ggsave(here::here("figures",  "105.png"))
   
 
# list of values to loop over
uniq_species = unique(factors$item)
uniq_species = unique(factors$fcode)
uniq_fcode <- unique(factors$fcode)
# Loop
 
for (i in 1:length(uniq_species)) {
 
  temp_plot = ggplot(data= subset(factors, item == uniq_species[i])) +
    geom_bar(size=3, aes(x=reorder(unit, -ihs4factor_n), y=ihs4factor_n ), stat = "identity") +
    coord_flip() +
    labs(y = "Unit conversion factor to kg") +
    ggtitle(uniq_species[i]) 

  ggsave(temp_plot, file=here::here("figures", paste0("plot_",uniq_fcode[i],".png")), width = 14, height = 10, units = "cm")
}
```


```{r}
library(ggplot2)
library(plyr)      # for dlply
library(gridExtra) # for marrangeGrob


factors <- read.csv(here::here("inter-ouput", "factors3.csv"))
factors <- subset(factors, item != "")

# list of values to loop over
uniq_species = unique(factors$item)

# Loop
for (i in uniq_species) {
  
  temp_plot = ggplot(data= subset(factors, item == i)) + 
    geom_bar(size=3, aes(x=reorder(unit, -ihs4factor_n), y=ihs4factor_n ), stat = "identity") +
    labs(y = "Unit conversion factor to kg") +
    ggtitle(i) + 
    coord_flip() +
    labs(y = "Unit conversion factor to kg")
  
  ggsave(temp_plot, file=here::here("figures", paste0("plot_", i,".png")), width = 14, height = 10, units = "cm")
}
 
# Create pdf doc of plots
plots <- dlply(factors, ~fcode,
               function(x)
                 ggplot(data = x) + 
                 geom_bar(aes(reorder(unit, -ihs4factor_n), y=ihs4factor_n ), stat = "identity") +
                 labs(subtitle = x$item) + xlab("") + ylab("Unit conversion factor to kg") + coord_flip() +
                 theme(plot.title = element_text(hjust = 0.5),
                       plot.subtitle = element_text(hjust = 0.5)) + theme_bw()) 
mg <- marrangeGrob(grobs = plots, nrow=2, ncol=2, top = NULL)
ggsave(here::here("figures", "plotdoc.pdf"), mg, height = 7, width = 13, units = "in")

```